"""id integer to biginteger

Revision ID: bcc794104101
Revises: 77c96a061d09
Create Date: 2026-03-19 10:14:01.628526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc794104101'
down_revision: Union[str, Sequence[str], None] = '77c96a061d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'application_steps', 'application_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'application_steps', 'step_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'application_steps', 'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'application_steps', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'applications', 'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'applications', 'platform_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'applications', 'company_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'applications', 'old_company',
        existing_type=sa.VARCHAR(length=200),
        nullable=True
    )
    op.alter_column(
        'applications', 'last_step_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True
    )
    op.alter_column(
        'applications', 'feedback_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True
    )
    op.alter_column(
        'applications', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'companies', 'created_by',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True
    )
    op.alter_column(
        'companies', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'feedbacks_definition', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'platforms', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'quinzenal_reports', 'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'quinzenal_reports', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'steps_definition', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    op.alter_column(
        'users', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'steps_definition', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'quinzenal_reports', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'quinzenal_reports', 'user_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'platforms', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'feedbacks_definition', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'companies', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'companies', 'created_by',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    op.alter_column(
        'applications', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'applications', 'feedback_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    op.alter_column(
        'applications', 'last_step_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    op.alter_column(
        'applications', 'old_company',
        existing_type=sa.VARCHAR(length=200),
        nullable=False
    )
    op.alter_column(
        'applications', 'company_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'applications', 'platform_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'applications', 'user_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'application_steps', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'application_steps', 'user_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'application_steps', 'step_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'application_steps', 'application_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
